env: 
  global: 
    secure: OXTFUvTBSAdNIM1eInVOEpLGhyF0v0YHYSmDsRF6Z1Nc56Dzm+C7wT77DWmEF8s4SDi9RlRbsAZf32DPWRBJw7WQLNOjxYqQKI7Q14mxhCXKKvPxEBtZCPz6TlWb6xbiz3F36qNNmzakf+torxm8iwH6uavnglB8DvCNsj7nQZM=
before_install: git submodule update --init
script: make test
after_success:
  - curl https://gist.githubusercontent.com/wakaba/9970857/raw/travis-merger.pl | perl
notifications: 
  irc: 
    use_notice: true
    channels: 
      - irc.suikawiki.org#mechanize
  email: 
    - wakaba@suikawiki.org
deploy:
  provider: heroku
  api_key: "iWoCZqO/9SbEs8hw7l6ifdt3f7dJU4ABIA5iSzPX3HAftHSiy84D5Gax4Uu4bG5j4AkHKI+Gk3dYFs0G6mfi1bC3fcrRc4hnevMwgQECmcaK6NWjzqXXtCLNF9CrcRtA+7FkFxVnCXMJZClfLh4+AGrNOOa8o3N0/KKoJ8xGgOc="
  app:
    master: fuga1
  on:
    branch: master
